### ISSUE TITLE
jitescript fails to build with asm-debug-all

### ISSUE THREAD

**Issue by ebourg** [qmx/jitescript#15]
Hi,

I noticed that jitescript fails to build if the dependency on asm-all is replaced by asm-debug-all. Here is the error displayed:

    src/main/java/me/qmx/jitescript/MethodDefinition.java:[58,36] error: incompatible types: ArrayList<VisibleAnnotation> cannot be converted to List<AnnotationNode>
    src/main/java/me/qmx/jitescript/FieldDefinition.java:[25,34] error: incompatible types: ArrayList<VisibleAnnotation> cannot be converted to List<AnnotationNode>

This error doesn't happen with asm-all because the classes are stripped from the debug symbols and the generic signatures.

Maybe VisibleAnnotation should extend AnnotationNode so the list contains the type expected?

**Comment by headius** [comment]
That would make sense. I can try to fix it later but if you can PR a fix that would be helpful!

**Comment by tkoeppe** [comment]
I believe I have a fix for this, too, as we too found this. Would you like it?

**Comment by tkoeppe** [comment]
That's #20.
