### ISSUE TITLE
Code needs modernization for recent Java versions

### ISSUE THREAD

**Issue by tkoeppe** [qmx/jitescript#17]
Modern Java complains about "raw types" when types such as `Class` or `Enum` are used; those should perhaps nowadays be spelled `Class<?>` and `Enum<?>`. Would you like a pull request for such a change?

**Comment by headius** [comment]
Hey I did not see this issue... please do submit a PR!

I am doing a release that includes an automatic module name and other updates to build and run well on Java 11+ would be welcome.

**Comment by tkoeppe** [comment]
Done, that's #19!

I'd welcome if you could test this again on your end. I've only tested the change through its integration into our codebase, which might not cover all the platforms you intend to support!

**Comment by headius** [comment]
Thank you! I have merged both of your PRs and have pushed a testing branch of JRuby using a snapshot build. Assuming that looks good, I will push a 0.4.3 release.

**Comment by tkoeppe** [comment]
Thanks a lot!

**Comment by headius** [comment]
0.4.3 has been released!
